-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 13:46:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GameShop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GameShop` ;

-- -----------------------------------------------------
-- Schema GameShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GameShop` DEFAULT CHARACTER SET utf8 ;
USE `GameShop` ;

-- -----------------------------------------------------
-- Table `GameShop`.`Videojuegos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Videojuegos` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Videojuegos` (
  `id_videojuego` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `Precio` INT NOT NULL,
  `Categoria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_videojuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Proveedores` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Proveedores` (
  `id_proveedores` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `Telefono` INT NOT NULL,
  `Domicilio` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_proveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Tiendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Tiendas` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Tiendas` (
  `id_tiendas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Domicilio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tiendas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoP` VARCHAR(45) NOT NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `Fecha_Nacimiento` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Domicilio` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoP` VARCHAR(45) NOT NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `NSS` VARCHAR(45) NOT NULL,
  `Fecha_Nacimiento` VARCHAR(45) NOT NULL,
  `CURP` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Domicilio` VARCHAR(45) NOT NULL,
  `Sueldo` INT NOT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Compra` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Compra` (
  `id_videojuego` INT NOT NULL,
  `id_tienda` INT NOT NULL,
  `id_clientes` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Total` DOUBLE NOT NULL,
  `Fecha` DATE NOT NULL,
  INDEX `fk_Videojuegos_has_Tiendas_Tiendas1_idx` (`id_tienda` ASC) VISIBLE,
  INDEX `fk_Videojuegos_has_Tiendas_Videojuegos_idx` (`id_videojuego` ASC) VISIBLE,
  INDEX `fk_Compra_Clientes1_idx` (`id_clientes` ASC) VISIBLE,
  PRIMARY KEY (`id_videojuego`, `id_tienda`, `id_clientes`),
  CONSTRAINT `fk_Videojuegos_has_Tiendas_Videojuegos`
    FOREIGN KEY (`id_videojuego`)
    REFERENCES `GameShop`.`Videojuegos` (`id_videojuego`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Videojuegos_has_Tiendas_Tiendas1`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `GameShop`.`Tiendas` (`id_tiendas`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Compra_Clientes1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `GameShop`.`Clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Trabaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Trabaja` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Trabaja` (
  `id_tiendas` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `Hora_Entrada` TIME NOT NULL,
  `Hora_Salida` TIME NOT NULL,
  `Turno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tiendas`, `id_empleado`),
  INDEX `fk_Tiendas_has_Empleados_Empleados1_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `fk_Tiendas_has_Empleados_Tiendas1_idx` (`id_tiendas` ASC) VISIBLE,
  CONSTRAINT `fk_Tiendas_has_Empleados_Tiendas1`
    FOREIGN KEY (`id_tiendas`)
    REFERENCES `GameShop`.`Tiendas` (`id_tiendas`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tiendas_has_Empleados_Empleados1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `GameShop`.`Empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Proveen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Proveen` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Proveen` (
  `id_videojuego` INT NOT NULL,
  `id_proveedores` INT NOT NULL,
  `id_tiendas` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`id_videojuego`, `id_proveedores`, `id_tiendas`),
  INDEX `fk_Videojuegos_has_Proveedores_Proveedores1_idx` (`id_proveedores` ASC) VISIBLE,
  INDEX `fk_Videojuegos_has_Proveedores_Videojuegos1_idx` (`id_videojuego` ASC) VISIBLE,
  INDEX `fk_Proveen_Tiendas1_idx` (`id_tiendas` ASC) VISIBLE,
  CONSTRAINT `fk_Videojuegos_has_Proveedores_Videojuegos1`
    FOREIGN KEY (`id_videojuego`)
    REFERENCES `GameShop`.`Videojuegos` (`id_videojuego`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Videojuegos_has_Proveedores_Proveedores1`
    FOREIGN KEY (`id_proveedores`)
    REFERENCES `GameShop`.`Proveedores` (`id_proveedores`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Proveen_Tiendas1`
    FOREIGN KEY (`id_tiendas`)
    REFERENCES `GameShop`.`Tiendas` (`id_tiendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Atiende`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Atiende` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Atiende` (
  `id_tiendas` INT NOT NULL,
  `id_clientes` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `Fecha_Atencion` DATE NULL,
  PRIMARY KEY (`id_tiendas`, `id_clientes`, `id_empleado`),
  INDEX `fk_Tiendas_has_Clientes_Clientes1_idx` (`id_clientes` ASC) VISIBLE,
  INDEX `fk_Tiendas_has_Clientes_Tiendas1_idx` (`id_tiendas` ASC) VISIBLE,
  INDEX `fk_Atiende_Empleados1_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_Tiendas_has_Clientes_Tiendas1`
    FOREIGN KEY (`id_tiendas`)
    REFERENCES `GameShop`.`Tiendas` (`id_tiendas`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tiendas_has_Clientes_Clientes1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `GameShop`.`Clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Atiende_Empleados1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `GameShop`.`Empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GameShop`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GameShop`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `GameShop`.`Inventario` (
  `id_videojuego` INT NOT NULL,
  `id_tiendas` INT NOT NULL,
  `Stock` INT NOT NULL,
  PRIMARY KEY (`id_videojuego`, `id_tiendas`),
  INDEX `fk_Videojuegos_has_Tiendas_Tiendas2_idx` (`id_tiendas` ASC) VISIBLE,
  INDEX `fk_Videojuegos_has_Tiendas_Videojuegos1_idx` (`id_videojuego` ASC) VISIBLE,
  CONSTRAINT `fk_Videojuegos_has_Tiendas_Videojuegos1`
    FOREIGN KEY (`id_videojuego`)
    REFERENCES `GameShop`.`Videojuegos` (`id_videojuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Videojuegos_has_Tiendas_Tiendas2`
    FOREIGN KEY (`id_tiendas`)
    REFERENCES `GameShop`.`Tiendas` (`id_tiendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
