INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (1, 'Super Mario Bros', 799, 'Plataformas');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (2, 'The Legend of Zelda', 899, 'Aventura');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (3, 'FIFA 22', 1499, 'Deportes');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (4, 'Call of Duty', 1299, 'Acción');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (5, 'Minecraft', 1999, 'Sandbox');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (6, 'Warzone', 999, 'Battle Royale');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (7, 'Assassins Creed V', 499, 'Aventura');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (8, 'Overwatch', 299, 'Shooter');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (9, 'Rocket League', 499, 'Deportes');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (10, 'Grand Theft Auto V', 499, 'Mundo Abierto');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (11, 'Cyberpunk 2077', 999, 'RPG');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (12, 'League of Legends', 199, 'MOBA');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (13, 'Super Smash Bros', 699, 'Lucha');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (14, 'Skyrim', 599, 'RPG');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (15, 'PUBG', 999, 'Battle Royale');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (16, 'Uncharted 4', 899, 'Aventura');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (17, 'NBA 2K22', 1499, 'Deportes');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (18, 'Far Cry 6', 1299, 'Acción');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (19, 'The Sims 4', 1999, 'Simulación');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (20, 'Apex Legends', 999, 'Battle Royale');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (21, 'The Witcher 3', 499, 'RPG');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (22, 'Fortnite', 299, 'Shooter');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (23, 'FIFA 23', 499, 'Deportes');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (24, 'Dungeons', 699, 'Aventura');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (25, 'Resident Evil', 599, 'Horror');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (26, 'Cyberpunk 2088', 1199, 'RPG');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (27, 'Counter-Strike', 799, 'Shooter');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (28, 'Rocket League', 499, 'Deportes');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (29, 'Among Us', 299, 'Aventura');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (30, 'Stardew Valley', 899, 'Simulación');
INSERT INTO videojuegos (id_videojuego, Nombre, Precio, Categoria) VALUES (31, 'World of Warcraft', 1599, 'RPG');


INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (1, 'StockSup', 123456789, 'Calle Principal #123', 'stocksup@gmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (2, 'ProvGames', 987654321, 'Avenida Central #456', 'provgames@outlook.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (3, 'ArtGames', 555123456, 'Calle Secundaria #789', 'artgames@hotmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (4, 'TechSupplies', 111222333, 'Calle Tecnológica #456', 'techsupplies@gmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (5, 'ElectroMart', 444555666, 'Avenida Electrónica #789', 'electromart@hotmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (6, 'GamerTech', 777888999, 'Calle Gamer #101', 'gamertech@gmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (7, 'DigitalEmporium', 666555444, 'Avenida Digital #202', 'digitalemporium@outlook.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (8, 'InnoSupplies', 333222111, 'Calle de la Innovación #303', 'innosupplies@hotmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (9, 'SmartTech', 999888777, 'Avenida Inteligente #404', 'smarttech@gmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (10, 'TechTrends', 555666777, 'Calle de las Tendencias #505', 'techtrends@outlook.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (11, 'FutureSupplies', 111555999, 'Avenida Futura #606', 'futuresupplies@hotmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (12, 'MegaElectronics', 777333111, 'Calle Mega #707', 'megaelectronics@gmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (13, 'TechGurus', 222666888, 'Avenida Gurus #808', 'techgurus@hotmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (14, 'InnoTech', 888444222, 'Calle de la Innovación #909', 'innotech@gmail.com');
INSERT INTO proveedores (id_proveedores, Nombre, Telefono, Domicilio, Correo) VALUES (15, 'DigitalWorld', 444999666, 'Avenida Digital #1010', 'digitalworld@outlook.com');

INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (1, 'GameCenter', 'Calle Maya #123');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (2, 'Best Buy', 'Avenida Principal #456');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (3, 'EB Games', 'Calle del Juego #789');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (4, 'Micro Center', 'Avenida Tecnológica #101');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (5, 'Fry Electronics', 'Calle Electrónica #202');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (6, 'GameSpot', 'Avenida Gamer #303');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (7, 'Digital Game', 'Calle Digital #404');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (8, 'StoreTech', 'Avenida de la Innovación #505');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (9, 'SmartBuy', 'Calle Inteligente #606');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (10, 'Trendy Games', 'Avenida de las Tendencias #707');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (11, 'FutureGames', 'Calle Futura #808');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (12, 'MegaStoreGames', 'Avenida Mega #909');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (13, 'GuruGames', 'Calle de los Gurus #1010');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (14, 'GamesDV', 'Avenida de la Innovación #1111');
INSERT INTO tiendas (id_tiendas, Nombre, Domicilio) VALUES (15, 'DigitalGameStore', 'Calle Digital #1212');

INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (1, 'Juan', 'García', 'López', '1990-05-15', 555123456, 'Calle Hidalgo #123', 'juang@gmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (2, 'Pedro', 'Martínez', 'Sánchez', '1985-08-22', 555234567, 'Calle Morelos #456', 'pedrom@outlook.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (3, 'Arturo', 'Hernández', 'Ramírez', '1992-02-10', 555345678, 'Calle Cárdenas #789', 'arturor@hotmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (4, 'Laura', 'Rodríguez', 'Gómez', '1988-11-30', 555456789, 'Calle Aztecas #101', 'laurarg@gmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (5, 'Ana', 'Pérez', 'Mendoza', '1995-04-05', 555567890, 'Calle Zapata #202', 'anapm@outlook.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (6, 'Carlos', 'Santos', 'Ríos', '1982-07-18', 555678901, 'Calle Benito Juárez #303', 'carlossr@hotmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (7, 'Isabel', 'Vargas', 'Ortiz', '1998-09-25', 555789012, 'Calle Madero #404', 'isabelvo@gmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (8, 'Miguel', 'Gutiérrez', 'Castro', '1980-03-12', 555890123, 'Calle Cuauhtémoc #505', 'miguelgc@outlook.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (9, 'Sofía', 'Cabrera', 'Lara', '1993-06-20', 555901234, 'Calle Guerrero #606', 'sofiacLara@hotmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (10, 'Alejandro', 'Ramos', 'Díaz', '1987-01-08', 555012345, 'Calle Reforma #707', 'alejandrorD@gmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (11, 'Elena', 'Guerrero', 'Soto', '1996-12-02', 555123456, 'Calle Allende #808', 'elenagsoto@gmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (12, 'Ricardo', 'Cruz', 'Fernández', '1983-04-28', 555234567, 'Calle Victoria #909', 'ricardocf@gmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (13, 'María', 'Sánchez', 'Molina', '1991-10-15', 555345678, 'Calle Ignacio Zaragoza #1010', 'mariasm@gmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (14, 'Héctor', 'Gómez', 'Pérez', '1986-05-08', 555456789, 'Calle Galeana #1111', 'hectorgp@gmail.com');
INSERT INTO clientes (id_clientes, Nombre, ApellidoP, ApellidoM, Fecha_Nacimiento, Telefono, Domicilio, Correo) VALUES (15, 'Patricia', 'Fuentes', 'Sosa', '1994-08-12', 555567890, 'Calle Madero #1212', 'patriciafs@gmail.com');

INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (1, 'José', 'González', 'López', '123456789', '1985-07-15', 'GOLJ850715HDFNNS09', 555123456, 'Calle París #123', 2200);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (2, 'Diego', 'Martínez', 'Sánchez', '987654321', '1990-02-22', 'MASD900222HDFMRG07', 555234567, 'Calle Londres #456', 2300);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (3, 'Luis', 'Hernández', 'Ramírez', '567890123', '1988-11-30', 'HERL881130HDFNMS04', 555345678, 'Calle Nueva York #789', 2400);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (4, 'Ana', 'Rodríguez', 'Gómez', '012345678', '1992-04-05', 'ROGA920405HDFNNA02', 555456789, 'Calle Aztecas #101', 2500);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (5, 'María', 'Pérez', 'Mendoza', '678901234', '1983-07-18', 'PEMM830718HDFRRA03', 555567890, 'Calle Nueva Orleans #202', 2200);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (6, 'Juan', 'Santos', 'Ríos', '345678901', '1995-09-25', 'SARJ950925HDFNTN05', 555678901, 'Calle Roma #303', 2300);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (7, 'Elena', 'Vargas', 'Ortiz', '890123456', '1980-03-12', 'VAOE800312HDFGLN06', 555789012, 'Calle Madrid #404', 2400);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (8, 'Ricardo', 'Gutiérrez', 'Castro', '456789012', '1993-06-20', 'GUCR930620HDFRTS08', 555890123, 'Calle Barcelona #505', 2500);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (9, 'Sofía', 'Cabrera', 'Lara', '234567890', '1987-01-08', 'CALF870108HDFBRS09', 555901234, 'Calle Berlín #606', 2200);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (10, 'Alejandro', 'Ramos', 'Díaz', '901234567', '1996-12-02', 'RADL961202HDFPLA01', 555012345, 'Calle París #707', 2300);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (11, 'Isabel', 'Guerrero', 'Soto', '678012345', '1982-04-28', 'GUIS820428HDFRSL02', 555123456, 'Calle Moscú #808', 2400);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (12, 'Miguel', 'Cruz', 'Fernández', '345678901', '1991-10-15', 'CUFM911015HDFNNG03', 555234567, 'Calle Sidney #909', 2500);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (13, 'Laura', 'Sánchez', 'Molina', '012345678', '1986-05-08', 'SAML860508HDFNLR04', 555345678, 'Calle Tokio #1010', 2200);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (14, 'Héctor', 'Gómez', 'Pérez', '789012345', '1994-08-12', 'GOPH940812HDFHRR05', 555456789, 'Calle Pekín #1111', 2300);
INSERT INTO empleados (id_empleado, Nombre, ApellidoP, ApellidoM, NSS, Fecha_Nacimiento, CURP, Telefono, Domicilio, Sueldo) VALUES (15, 'Patricia', 'Fuentes', 'Sosa', '456789012', '1989-02-20', 'FUSP890220HDFNTR06', 555567890, 'Calle El Cairo #1212', 2400);
